services:
  catalogue:
    image: catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb

  mongodb:
    image: mongodb:v1
    container_name: mongodb
  
  redis:
    image: redis:7
    conatiner_name: redis

  

networks:
  default:
    driver: bridge
    name: roboshop
    external: false    # true if the network is created manually using docker network command
