services:
  mongodb:
    image: mongodb:v1
    conatiner_name: mongodb

networks:
  default:
    driver: bridge
    name: roboshop
    external: false    # true if the network is created manually using docker network command
